### ISSUE TITLE
Bug with the dual wave

### ISSUE THREAD

**Issue by KingStickmin** [nytelytee/geode-wave-trail-drag-fix#1]
When I was playing deadlocked. I got to the dual wave and it bugged. It looked like the wave trail was connected to both waves. Develepoe, please fix this!

**Comment by nytelytee** [comment]
This is fixed by commit b1665b4a816aa9f62812fe35fd9fdaf8ed5cbd9a. The update is currently pending to be put onto the index. If you can't wait, you can install it manually from the releases page.
