### ISSUE TITLE
GD 2.206 port?

### ISSUE THREAD

**Issue by Myron472** [nytelytee/geode-wave-trail-drag-fix#10]
GD 2.206 port?

**Comment by NotGumballer91** [comment]
maintainer is inactive for 2 months :(

**Comment by nytelytee** [comment]
Sorry, my PC is in pieces right now because I took it apart before checking if I have thermal paste or not, when I get it back together and when I have the time I'll start working on it.

**Comment by LumerGD120** [comment]
It's released!
