### ISSUE TITLE
Weird wave + teleport portal interaction

### ISSUE THREAD

**Issue by Fnige** [nytelytee/geode-wave-trail-drag-fix#12]
![image](https://github.com/user-attachments/assets/3387c7c8-9dbe-4930-b04f-746c84c27e88)

As shown in the picture, this time you can recreate this within Dear Nostalgists (18735780) at this point. At least recreating this is through a 3 minute level instead of a 55 minute one :3

**Comment by nytelytee** [comment]
Fixed in v1.4.0.
