### ISSUE TITLE
Little bug

### ISSUE THREAD

**Issue by GoldenToast89** [nytelytee/geode-wave-trail-drag-fix#2]
When the wave touches the roof or the floor it makes a weird efect

![wave_bug](https://github.com/nytelytee/geode-wave-trail-drag-fix/assets/126029212/fc052507-4453-48c5-9560-c793055b2056)

**Comment by nytelytee** [comment]
I have no idea what causes that. It only seems to happen on some FPS, I was using 360 when I was testing the mod so I didn't notice. No idea how to fix it, I will try to figure it out eventually.

**Comment by GoldenToast89** [comment]
Ok, no problem

**Comment by nytelytee** [comment]
Try to download the latest artifact from the Actions section on the repo and see if this fixes the slant issue. I am probably not going to push it out as an update since I plan to rewrite the entire mod to make it work on more cases (try the current version on moving blocks, it does not work lol).

**Comment by nytelytee** [comment]
The slant is fixed in v1.0.3, which was never actually published to the index, in favor of v1.1.0, which does the calculation completely differently. Since it's fixed in both cases, I am closing this.
