### ISSUE TITLE
Suddenly appearing wave trail

### ISSUE THREAD

**Issue by Fnige** [nytelytee/geode-wave-trail-drag-fix#4]
![image](https://github.com/nytelytee/geode-wave-trail-drag-fix/assets/35159947/fc948c35-bf2b-4c53-bb08-516154fb4938)
Idk why this happens but you can remake it consistently by completing Eon in practise mode.

**Comment by nytelytee** [comment]
I think I forgot to check if the gamemode is wave at the end, when adding an extra point before the end animation starts. Try it with the latest artifact after it finishes building. If it works I'll release the next version.

**Comment by Fnige** [comment]
Yep seems to work, thank you!
