### ISSUE TITLE
interaction with spider orb

### ISSUE THREAD

**Issue by ChromaTK** [nytelytee/geode-wave-trail-drag-fix#6]
without mod:
![2024-03-24 22-43-22 0](https://github.com/nytelytee/geode-wave-trail-drag-fix/assets/117107593/77995c32-6ff4-4ed7-b35f-f9cbb4404e99)
with mod:
![2024-03-24 22-43-55 0](https://github.com/nytelytee/geode-wave-trail-drag-fix/assets/117107593/873fa39d-cfc1-4bb4-a9a8-22a6e302c52e)

not fixed by the actions tab version
level id is 98682727

**Comment by nytelytee** [comment]
Fixed
