### ISSUE TITLE
Jump orbs mess up the wave trail

### ISSUE THREAD

**Issue by Fornax985** [nytelytee/geode-wave-trail-drag-fix#8]
https://github.com/nytelytee/geode-wave-trail-drag-fix/assets/158332200/ed3dea53-a48e-488e-9786-0df5e87c1d5d

**Comment by edwloef** [comment]
Can confirm this happens to me as well

Uploading untitled.mp4…

**Comment by edwloef** [comment]
The issue seems to be fixed now in v1.2.5

**Comment by nytelytee** [comment]
lol i was just typing that it was fixed now and got this comment in real time
